# Generated by Django 3.1.2 on 2020-11-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(max_length=50, unique=True)),
                ('usuario_password', models.CharField(max_length=255)),
                ('usuario_tipo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solicitud_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('solicitud_cantidad', models.BigIntegerField()),
                ('solicitud_tipo', models.CharField(max_length=15)),
                ('solicitud_ubicacion', models.CharField(max_length=1000)),
                ('licitacion_productor_inicio', models.DateTimeField(auto_now=True)),
                ('licitacion_productor_fin', models.DateField(blank=True, null=True)),
                ('licitacion_transporte_inicio', models.DateField(blank=True, null=True)),
                ('licitacion_transporte_fin', models.DateField(blank=True, null=True)),
                ('solicitud_fecha', models.DateField()),
                ('solicitud_comentario', models.CharField(max_length=4000)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lic.usuario')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
    ]
